name: 'Post service metrics to Mackerel'
description: 'This is a simple action that posts service metrics to Mackerel (https://mackerel.io/).'
author: 'stefafafan'
inputs:
  api-key:
    required: true
    description: 'API Key value of Mackerel. Should be stored in GitHub Secrets.'
  service-name:
    required: true
    description: 'The Mackerel service name you want to post metrics to.'
  metric-name:
    required: false
    description: 'The Mackerel metric name you want to post. Accepted values are [a-zA-Z0-9._-]+ . Either this or metrics is required.'
  metric-value:
    required: false
    description: 'The Mackerel metric value you want to post. Should be a numeric value. Required when specifying metric-name.'
  metrics:
    required: false
    description: 'Use this to specify multiple metrics at once. Formatted as "name value timestamp".'
outputs:
  time:
    description: 'The time used to post the metric (epoch seconds).'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'blue'
