name: Multiline output example

on:
  push

jobs:
  count-and-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: multiline-output
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "metrics<<${delimiter}" >> $GITHUB_OUTPUT
          echo "multiline.output1 12345" >> $GITHUB_OUTPUT
          echo "multiline.output2 67890" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      # Post metrics sent from multiline output of previous step.
      - name: Post to Mackerel
        uses: stefafafan/post-mackerel-metrics@v1
        with:
          api-key: ${{ secrets.MACKEREL_APIKEY }}
          service-name: ${{ secrets.MACKEREL_SERVICENAME }}
          metrics: ${{ steps.multiline-output.outputs.metrics }}
